name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Display current directory
        run: ./gateway/pwd
      - name: List contents of current directory
        run: ./gateway/ls -al
      - name: Install dependencies
        run: ./gateway/npm install
      - name: Create build
        run: ./gateway/npm run build --if-present
